name: publisher
on:
  workflow_dispatch:
  push:
    tags:
      - "**"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Tidy
        run: go mod tidy

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -race -v -o watchparty main.go

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -race -v -o watchparty.exe main.go

      - name: Publish
        run: gh release create "$GITHUB_REF_NAME" watchparty watchparty.exe --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
