name: publisher
on:
  workflow_dispatch:
  push:
    tags:
      - "**"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Tidy
        run: go mod tidy

      - name: Build Linux
        run: GOOS=linux go build -v main.go -o watchparty

      - name: Build Windows
        run: GOOS=windows go build -v main.go -o watchparty.exe

      - name: Publish
        run: gh release "$GITHUB_REF_NAME" watchparty watchparty.exe --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
